### ISSUE TITLE
i failed to boot on this message

### ISSUE THREAD

**Issue by kimyw3007** [minos-project/minos-hypervisor#4] opened 2019-01-08 16:57 UTC
i follow up "Boot the Raspberry to the u-boot commandline environment, execute the following command to start the system"

but i just saw under this picture (on raspberry pie 3 plus display)
![linuxonrasp](https://user-images.githubusercontent.com/45417960/50846593-e21a6d80-13b2-11e9-940c-8c559a9bb699.jpg)

How will i boot with u-boot commandline on raspberrypie right way?

please tell me solution 

Thank you for reading

**Comment by minos-project** [comment] 2019-01-09 10:58
After U-boot starts, it waits for three seconds by default. If it does not press any button/key within three seconds, u-boot will start automatically. The current automatic startup uses the network startup mode, so the phenomenon in your picture will appear. there are two solutions

1: do not using display as an the console, connect a usb-to-uart cable, to use the UART as the debug console
2: using the display, and connect an USB keyboard

but currently, the debian system provide by me did not add the display parameter in the cmdline, so you'd better connect an USB-to-UART cable as the debug console.

**Comment by minos-project** [comment] 2019-01-09 11:20
actually, you are already at the command line mode, but because you do not connect a keyboard, so you can not type anything.

**Comment by kimyw3007** [comment] 2019-01-11 02:46
no i already connect keyboard but it didnt work on minos.. i cannot type anything but if i used another sd card(rasppi os or aosp) it worked well. I think keyboard just didnt work in this situation even though it is connected

**Comment by minos-project** [comment] 2019-01-11 03:20
rasppi os or aosp do not use u-boot to load the kernel.

It seems u-boot do not support USB keyboard for raspberry PI 3b+ now.  if you do not have UART cable, you can follow below step to let u-boot to boot Linux from sdcard and load minos.bin by default.

1: add below new config into **u-boot/configs/rpi_3_defconfig**, the recompile the u-boot
      CONFIG_BOOTCOMMAND="fatload mmc 0:1 0x28000000 minos.bin; fatload mmc 0:1 0x03e00000 bcm2837-rpi-3-b-plus.dtb; fatload mmc 0:1 0x00080000 Image; booti 0x28000000 - 0x03e00000"

2: make CROSS_COMPILE=aarch64-linux-gnu- rpi_3_defconfig
3: make CROSS_COMPILE=aarch64-linux-gnu- -j4

then copy the new u-boot.bin to your sdcard.

but you need to connect a UART cable, since I did not test minos with a display via HDMI, there may be nothing output if there is no UART.

but you can try to modify the command line in hypervisor/config/raspberry3/raspberry3.json.cc to enable the VideoCore to use the display.

**Comment by minos-project** [comment] 2019-01-16 09:39
Yes, you can try like the Youtube shows if you are using windows environment.

**Comment by kimyw3007** [comment] 2019-01-16 09:41
Hi! first, Thank you for everything

Today i success to install this minos on raspberry pi 3 b+ through uart interface

(i used usb to uart interface and i connected to my pc through usb portand type uboot fatload on putty it worked well)

but i faced another problem when i repluged this usb

problem is like this below image

![image](https://user-images.githubusercontent.com/45417960/51240023-37134080-19be-11e9-80c3-2d19b0927d86.png)


i don't know why it happend again in serial communication 

Thank you for reading

**Comment by minos-project** [comment] 2019-01-16 11:47
----- but i faced another problem when i repluged this usb
[question] when do you repluged the usb-uart ? after you type all the fatload command or booti command ?

You need to type anything at the stage of u-boot booting, otherwise the u-boot will enter into auto booting mode (after 3 seconds) which using network boot as default. 

you can modify your u-boot to let u-boot to boot minos as default:

1: add below new config into u-boot/configs/rpi_3_defconfig, the recompile the u-boot
CONFIG_BOOTCOMMAND="fatload mmc 0:1 0x28000000 minos.bin; fatload mmc 0:1 0x03e00000 bcm2837-rpi-3-b-plus.dtb; fatload mmc 0:1 0x00080000 Image; booti 0x28000000 - 0x03e00000"

2: make CROSS_COMPILE=aarch64-linux-gnu- rpi_3_defconfig
3: make CROSS_COMPILE=aarch64-linux-gnu- -j4

then copy the new u-boot.bin to your sdcard and rename it to kernel8.img.

**Comment by kimyw3007** [comment] 2019-01-16 15:44
And actually i tried again you already mentioned method, but i cannot type anything through putty

it seems wired.. i don't understand why first time i can type through putty on u-boot cmdline

but now after repluged, i cannot type anything and i followed new process (modify config cmd), it can work but i cannot type after booting.. T.T.. i don't want to go back first step 

please help me

Thank you for everything

**Comment by minos-project** [comment] 2019-01-17 02:12
> [answer] after below line
> 
> 1. Boot system with Minos support
> 
> Boot the Raspberry to the u-boot commandline environment, execute the following command to start the system
> 
> fatload mmc 0:1 0x28000000 minos.bin
> fatload mmc 0:1 0x03e00000 bcm2837-rpi-3-b-plus.dtb
> fatload mmc 0:1 0x00080000 Image
> booti 0x28000000 - 0x03e00000
> 
> i completed to do above command and success login with jiangxianxu
> 
> and then i just repluged my raspberry pi3 b+ (disconnecting usb-uart and connect again)
> 
> and then i faced above screenshot i already mentioned
> 
> Thank you for reading

From this message, actually you have successfully enable Minos on the raspberry pi3 b+.

> but now after repluged, i cannot type anything and i followed new process (modify config cmd), it can 
> work but i cannot type after booting on putty(before i can type).. T.T.. i don't want to go back first step

You do not need to go back first step, this issue is not caused by the code or the config, since you have already login into the VM0. the reason that you can not type anything may caused by:

1: after replug the uart , you need to change the COM port on your putty setting. 
2: please check the UART hardware connection on your RPI board.

If you have Ubuntu, you can use Minicom as the TTY tool which is better than putty.

**Comment by kimyw3007** [comment] 2019-01-17 02:18
i already checked 1 and 2 and actually suddenly it worked 

so..I confused i was just waiting almost 1hour after just connecting usb-uart and then i can type on putty.

and i faced another issue below picture

![image](https://user-images.githubusercontent.com/45417960/51291128-78046700-1a49-11e9-8f80-b8c93f88fa38.png)

you already write "./mvm -c 2 -m 96M -i boot64.img -n elinux64 -t linux -b 64 -v -r -d --gicv2 --eralyprintk -V virtio_console,@pty: -V virtio_blk,/home/jiangxianxu/sd.img -V virtio_net,tap0 -C "console=hvc0 loglevel=8 consolelog=9 root=/dev/vda2 rw" in documentation 

so i just tried this but i faced this message (unrecognized option '--eralyprintk')

Why did it happen?

Thank you for reading

**Comment by minos-project** [comment] 2019-01-17 04:10
you need add sudo 

**_sudo ./mvm_** -c 2 -m 96M -i boot64.img -n elinux64 -t linux -b 64 -v -r -d --gicv2 --eralyprintk -V virtio_console,@pty: -V virtio_blk,/home/jiangxianxu/sd.img -V virtio_net,tap0 -C "console=hvc0 loglevel=8 consolelog=9 root=/dev/vda2 rw"

**Comment by minos-project** [comment] 2019-01-17 04:13
and there is a mistake in the Readme.md

it should **_--earlyprintk_**

Thanks for your reminder. I will correct the Readme.md later

**Comment by minos-project** [comment] 2019-01-17 04:15
and do not forget to download the sd.img using below command, if you need to use virtio-blk image as the rootfs (-V virtio_blk,/home/jiangxianxu/sd.img)

    # wget http://leyunxi.com/static/sd.img

**Comment by kimyw3007** [comment] 2019-01-17 07:43
Hi i am glad to success creating vm

![image](https://user-images.githubusercontent.com/45417960/51302753-9fbdf400-1a76-11e9-80c5-89caadfbc4ef.png)


It seems like definetly success

but i just have quriosity of this 

![image](https://user-images.githubusercontent.com/45417960/51302836-e7dd1680-1a76-11e9-8f1e-c305dba86aa0.png)


point is warning in above capture

thank you for reading

**Comment by minos-project** [comment] 2019-01-17 08:31
Yes Congratulations. you have successfully create virtual machines. you can use minicom /dev/pts/1 to login to the VM.

for the virtio-net, each tap device can only be assign to one VM. so you need to change the name of the tap device. for example, tap0 for vm1, then tap1 for vm2.... (**-V virtio_net,tapX**)

But the virtio-net have some known issue and can not fully work now.

**Comment by kimyw3007** [comment] 2019-01-17 08:47
Thank you for reply

and actually our goal is we will mount AOSP on minos. i really hope this

but i will use another board for this purpose (maybe hikey 970) 

so i hope to support me for long term :)

I want to expand this project to bare metal virtualization market

Thank you !

**Comment by minos-project** [comment] 2019-01-17 09:42
Sure, no problem.

Now, I am refactor the whole code base for better porting to another platform. hope this refactor can help you porting Minos to Hikey 970 easier.

**Comment by kimyw3007** [comment] 2019-01-17 09:56
thank you for every comment i will be back soon! see you again

**Closed** 2019-01-18 10:51 UTC
